/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.mykingdom.mupdf;

import java.io.File;
import java.util.HashMap;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.KrollProxyListener;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.TiFileProxy;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;

import com.artifex.mupdflib.FilePicker;
import com.artifex.mupdflib.MuPDFCore;
import com.artifex.mupdflib.MuPDFPageAdapter;
import com.artifex.mupdflib.MuPDFReaderView;
import com.artifex.mupdflib.PageView;
import com.artifex.mupdflib.SearchTask;
import com.artifex.mupdflib.SearchTaskResult;
import com.artifex.mupdflib.FilePicker.FilePickerSupport;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Context;
import android.net.Uri;
import android.os.Message;
import android.content.DialogInterface;
import android.os.Bundle;
import android.widget.EditText;
import android.view.inputmethod.EditorInfo;
import android.text.method.PasswordTransformationMethod;
import android.content.res.Resources;

import android.os.CancellationSignal;
import java.io.File;
import java.io.FileDescriptor;
import android.os.ParcelFileDescriptor;
import java.io.OutputStream;
import java.io.InputStream;
import java.io.FileOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.FileNotFoundException;
import android.print.PageRange;
import android.print.PrintAttributes;
import android.print.PrintDocumentAdapter;
import android.print.PrintDocumentInfo;
import android.print.PrintManager;
import android.print.pdf.PrintedPdfDocument;

// This proxy can be created by calling Mupdf.createPDFReader({file: "path"})
@Kroll.proxy(creatableInModule = MupdfModule.class)
public class ViewProxy extends TiViewProxy {

	// Standard Debugging variables
	private static final String TAG = "PDFReaderProxy";

	private static final int MSG_FIRST_ID = TiViewProxy.MSG_LAST_ID + 1;
	private static final int MSG_SET_CURRENT_PAGE = MSG_FIRST_ID + 100;

	private class PDFReaderView extends TiUIView implements FilePickerSupport {

		private MuPDFReaderView mDocView;
		private MuPDFCore core;
		private SearchTask mSearchTask;
		private KrollFunction mSearchCallback;
		private KrollFunction mPrintCallback = null;
		private KrollFunction mSuccessCallback = null;
		private TiApplication tiApplication;
		private int currentPage;
		private int pageCount;
		private boolean renderResult = false;
		private File file;
		private boolean needsPassword = false;

		public PDFReaderView(TiViewProxy proxy) {

			super(proxy);

			tiApplication = TiApplication.getInstance();

			mDocView = new MuPDFReaderView(getActivity()) {
				@Override
				protected void onMoveToChild(int i) {
					currentPage = i + 1;
					if (getProxy().hasListeners(TiC.EVENT_CHANGE)) {
						KrollDict data = new KrollDict();
						data.put(TiC.PROPERTY_CURRENT_PAGE, currentPage);
						data.put(TiC.PROPERTY_COUNT, pageCount);
						getProxy().fireEvent(TiC.EVENT_CHANGE, data);
					}
					super.onMoveToChild(i);
				}

				@Override
				protected void onTapMainDocArea() {
					if (getProxy().hasListeners(TiC.EVENT_CLICK)) {
						getProxy().fireEvent(TiC.EVENT_CLICK, null);
					}
				}
			};
		}

		@Override
		public void processProperties(KrollDict d) {

			if (d.containsKey(TiC.PROPERTY_FILE)) {
				try {
					TiFileProxy fileProxy = (TiFileProxy) d
							.get(TiC.PROPERTY_FILE);
					file = fileProxy.getBaseFile().getNativeFile();
					if (file.exists()) {
						Log.d(TAG, "PDF exists, trying to load");
						core = openFile(Uri.decode(Uri.fromFile(file).getEncodedPath()));

						needsPassword = core.needsPassword();

						if (core != null && needsPassword) {
							Log.d(TAG, "core.needsPassword");
							requestPassword(getActivity());
							return;
						}
						else {
							Log.d(TAG, "!core.needsPassword");
							createUI(getActivity());
						}
					}
				} catch (Exception ex) {
					String err = (ex.getMessage() == null) ? "Something wrong with the file given"
							: ex.getMessage();
					Log.e(TAG, err);
				}
			}

			super.processProperties(d);
		}

		private void createUI(Activity activity){

			LayoutArrangement arrangement = LayoutArrangement.DEFAULT;

			if (proxy.hasProperty(TiC.PROPERTY_LAYOUT)) {
				String layoutProperty = TiConvert.toString(proxy
						.getProperty(TiC.PROPERTY_LAYOUT));
				if (layoutProperty.equals(TiC.LAYOUT_HORIZONTAL)) {
					arrangement = LayoutArrangement.HORIZONTAL;
				} else if (layoutProperty.equals(TiC.LAYOUT_VERTICAL)) {
					arrangement = LayoutArrangement.VERTICAL;
				}
			}

			TiCompositeLayout view = new TiCompositeLayout(proxy.getActivity(),
					arrangement);
			view.addView(mDocView);
			Log.d(TAG, "setNativeView");
			setNativeView(view);

			mDocView.setAdapter(new MuPDFPageAdapter(activity, this, core));
			pageCount = core.countPages();
			currentPage = 1;
			fireEvent("successEvent", new HashMap());
			Log.d(TAG,"[pdfreader] successEvent fired");
		}

		public void cleanup() {
			mDocView.releaseViews();
			core.onDestroy();
			core = null;
			mSearchTask = null;
			mDocView = null;
			mSearchCallback = null;
			mSuccessCallback = null;
			mPrintCallback = null;
		}

		private EditText mPasswordView;
		private AlertDialog.Builder mAlertBuilder;

		public void requestPassword(Activity activity) {
			mAlertBuilder = new AlertDialog.Builder(activity);
			mPasswordView = new EditText(activity);
			mPasswordView.setInputType(EditorInfo.TYPE_TEXT_VARIATION_PASSWORD);
			mPasswordView.setTransformationMethod(new PasswordTransformationMethod());

			AlertDialog.Builder alert = new AlertDialog.Builder(activity);
			String packageName = proxy.getActivity().getPackageName();
			Resources resources = proxy.getActivity().getResources();
			int enter_password = resources.getIdentifier("enter_password", "string", packageName);
		  alert.setTitle(enter_password);
			alert.setView(mPasswordView);
			alert.setPositiveButton("OK",
					new DialogInterface.OnClickListener() {
				public void onClick(DialogInterface dialog, int which) {
					if (core != null){
						if (core.authenticatePassword(mPasswordView.getText().toString())) {
							createUI(getActivity());
						} else {
							requestPassword(getActivity());
						}
					}
					else {
						// Log.d(TAG, "core is null");
					}
				}
			});
			alert.setNegativeButton(resources.getIdentifier("cancel", "string", packageName),
					new DialogInterface.OnClickListener() {

				public void onClick(DialogInterface dialog, int which) {
					// finish();
				}
			});
			alert.show();
		}

		private MuPDFCore openFile(String path) {
			Log.d(TAG, "Trying to open " + path);
			try {
				core = new MuPDFCore(getActivity(), path);
				mSearchTask = new SearchTask(tiApplication, core) {

					@Override
					protected void onTextFound(SearchTaskResult result) {
						int count = result.searchBoxes != null ? result.searchBoxes.length
								: 0;
						int pageNumber = result.pageNumber + 1;
						if (renderResult) {
							if (count != 0) {
								SearchTaskResult.set(result);
							}
							mDocView.setDisplayedViewIndex(result.pageNumber);
							mDocView.resetupChildren();
						}
						if (mSearchCallback != null) {
							HashMap<String, Object> params = new HashMap<String, Object>();
							params.put(TiC.PROPERTY_COUNT, count);
							params.put(TiC.PROPERTY_CURRENT_PAGE, pageNumber);
							mSearchCallback.call(getKrollObject(), params);
						}
					}
				};
			} catch (Exception e) {
				System.out.println(e);
				return null;
			}
			return core;
		}

		public boolean getNeedsPassword() {
			return needsPassword;
		}

		public int getPageCount() {
			return pageCount;
		}

		public void setCurrentPage(int pageNumber) {
			// pageNumber - converting 1 based index to 0
			mDocView.setDisplayedViewIndex(pageNumber - 1);
		}

		public int getCurrentPage() {
			return currentPage;
		}

		public void moveToNext() {
			if (core == null)
				return;
			mDocView.moveToNext();
		}

		public void moveToPrevious() {
			if (core == null)
				return;
			mDocView.moveToPrevious();
		}

		public void setScrollingDirectionHorizontal(boolean value){
			if (core == null)
				return;
			mDocView.setScrollingDirectionHorizontal(value);
		}

		public void onSearch(KrollFunction callback) {
			mSearchCallback = callback;
		}

		public void onPrint(KrollFunction callback) {
			mPrintCallback = callback;
		}

		public void onSuccess(KrollFunction callback) {
			Log.d(TAG, "onSuccess");
			mSuccessCallback = callback;
		}

		public void search(String key, int pageNumber, boolean showResult) {
			if (mSearchTask == null)
				return;
			renderResult = showResult;
			mSearchTask.go(key, 0, currentPage - 1, pageNumber - 1);
		}

		public void print() {
			Log.d(TAG, "print");

			PrintManager printManager = (PrintManager) getActivity().getSystemService(Context.PRINT_SERVICE);
			String jobName = "Document";

			PrintDocumentAdapter pda = new PrintDocumentAdapter(){

			    @Override
			    public void onWrite(PageRange[] pages, ParcelFileDescriptor destination, CancellationSignal cancellationSignal, WriteResultCallback callback){
			        InputStream input = null;
			        OutputStream output = null;

			        try {

			            input = new FileInputStream(file);
			            output = new FileOutputStream(destination.getFileDescriptor());

			            byte[] buf = new byte[1024];
			            int bytesRead;

			            while ((bytesRead = input.read(buf)) > 0) {
			                 output.write(buf, 0, bytesRead);
			            }

			            callback.onWriteFinished(new PageRange[]{PageRange.ALL_PAGES});

			        } catch (FileNotFoundException ee){
			            //Catch exception
			        } catch (Exception e) {
			            //Catch exception
			        } finally {
			            try {
			                input.close();
			                output.close();
			            } catch (IOException e) {
			                e.printStackTrace();
			            }
			        }
			    }

			    @Override
			    public void onLayout(PrintAttributes oldAttributes, PrintAttributes newAttributes, CancellationSignal cancellationSignal, LayoutResultCallback callback, Bundle extras){

			        if (cancellationSignal.isCanceled()) {
			            callback.onLayoutCancelled();
			            return;
			        }
							String jobName = "Document";
			        PrintDocumentInfo pdi = new PrintDocumentInfo.Builder(jobName).setContentType(PrintDocumentInfo.CONTENT_TYPE_DOCUMENT).build();
			        callback.onLayoutFinished(pdi, true);
			    }
			};

			printManager.print(jobName, pda, null);

		}

		public void setHighlightColor(String color) {
			PageView.HIGHLIGHT_COLOR = TiConvert.toColor(color);
		}

		@Override
		public void performPickFor(FilePicker picker) {

		}

	}

	// Constructor
	public ViewProxy() {
		super();
	}

	@Override
	public TiUIView createView(Activity activity) {
		TiUIView view = new PDFReaderView(this);
		view.getLayoutParams().autoFillsHeight = true;
		view.getLayoutParams().autoFillsWidth = true;
		return view;
	}

	public PDFReaderView getPDFReaderView() {
		return (PDFReaderView) getOrCreateView();
	}

	@Override
	public void releaseViews() {
		getPDFReaderView().cleanup();
		super.releaseViews();
	}

	@Override
	public boolean handleMessage(Message msg) {
		switch (msg.what) {
		case MSG_SET_CURRENT_PAGE: {
			getPDFReaderView().setCurrentPage((Integer) msg.obj);
			return true;
		}
		default: {
			return super.handleMessage(msg);
		}
		}
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options) {
		super.handleCreationDict(options);
	}

	@Kroll.method
	public void loadPDFFromFile(TiFileProxy file) {
		setPropertyAndFire(TiC.PROPERTY_FILE, file);
	}

	@Kroll.getProperty @Kroll.method
  public boolean getNeedsPassword()
  {
    return getPDFReaderView().getNeedsPassword();
  }

	@Kroll.method
	public int getPageCount() {
		return getPDFReaderView().getPageCount();
	}

	@Kroll.method
	public void setCurrentPage(int pageNumber) {
		if (TiApplication.isUIThread()) {
			getPDFReaderView().setCurrentPage(pageNumber);
			return;
		}
		Message message = getMainHandler().obtainMessage(MSG_SET_CURRENT_PAGE,
				pageNumber);
		message.sendToTarget();
	}

	@Kroll.method
	public int getCurrentPage() {
		return getPDFReaderView().getCurrentPage();
	}

	@Kroll.method
	public void moveToNext() {
		getPDFReaderView().moveToNext();
	}

	@Kroll.method
	public void moveToPrevious() {
		getPDFReaderView().moveToPrevious();
	}

	@Kroll.method
	public void setScrollingDirection(int direction) {
		getPDFReaderView().setScrollingDirectionHorizontal(direction == MupdfModule.DIRECTION_HORIZONTAL);
	}

	@Kroll.method
	public void onSearch(KrollFunction callback) {
		getPDFReaderView().onSearch(callback);
	}

	@Kroll.method
	public void onSuccess(KrollFunction callback) {
		getPDFReaderView().onSuccess(callback);
	}

	@Kroll.method
	public void search(String key, int pageNumber,
			@Kroll.argument(optional = true) Object showResult) {
		boolean enable = false;
		if (showResult != null) {
			enable = TiConvert.toBoolean(showResult);
		}
		getPDFReaderView().search(key, pageNumber, enable);
	}

	@Kroll.method
	public void setHighlightColor(String color) {
		getPDFReaderView().setHighlightColor(color);
	}

	@Kroll.method
	public void print() {
		getPDFReaderView().print();
	}
}
